### ISSUE TITLE
Generate evidences for segments

### ISSUE THREAD

**Issue by piedup** [stratumn/fabricstore#6]
Currently blocks are hashed by concatenating transactions. An evidence could contain the transaction id, the channel id and the block height.

Coming releases of Fabric will hash block using a merle tree. At this point proof can be similar to tendering proofs (excluding appHash).

Fabricstore (or an additional client a la tmpop) could listen for block events and create proofs as it receives blocks.

**Comment by simonvadee** [comment]
deprecated.
